sudo: required
services:
- docker
script:
- docker-compose build authclient
- docker-compose run --rm authclient sh -c "yarn && yarn test"
notifications:
  slack:
    secure: fBTmMzYavKqd5o/NKFo0jkq4DAgvwOtfgvgAgX+HcDOLlbHhoadnG9d7EAJiWlfzGlI43msumFPx3MXjDFLkCzmmFhpFVYR550oStDpffTcYYU0YYnMykuKX2gbStQGxHhxkaoZGIksoz0dTZhU552cWqp2S20oI50bq9TxHx8vqS7/o6mqg6awjO0DNHvDyp2T4v3pVX7n7ghRFZDaEJmSGwKs4XVtJ5LcF3omq5HEm4r7QbNiplwvznnEBXtSAWo6rEe9ss2myL3NtMrVH1wAjSt7JDglOlOYxq7xVWFNFVlTVuUQDQumKnqLBMCNm4xGgdbxO4u21qq4PDxrKvwWTFbSupMlZpozr8gvjgeyilXwxJyxtSxav8hF0bQWBqn02jHQr4+32K+6xW2VFgy55JKPLXeu+tYxXyXtSipMoMSERX1RS3b5pIYtw9UopFzFpyxPHIjl+6T4joOj+mHDLsBN4FmYqT8jSUo1uwGGrTIxGynVz5z2xM+voHaalocVwtPg/687t4WcNGC3yBZCAw2ZOLfSGQDzOUoRsI8zi5dBgKPTZQkJxeQ5EuYuvwOsSNfuLUtkpLEW6yZG6A0GGjUdqWEgajTmkuDNS1q+9mad7cm7JDrXK6aFUyRwlW0eZgHvqEeoqKofncSoWFqtdGlJ24m3RUgxcyBP8+B4=
