sudo: required
services:
- docker
script:
- docker-compose build authclient
- docker-compose run --rm authclient sh -c "yarn && yarn test"
notifications:
  slack:
    secure: KEXv5ficzsYbTEAy4lsNaur66pV0W6bZ0GW5LfTUsr95vBN+bIpcg89CfYbYKshrA1dduWNHLlASxnXjDGG6XZoFulH3b04/qnRCBmYIFw2IJsdYiagouJwe0IEfAhx9MDxhVYwop3If3aTJeXVRFg3ApHa/Ao1LAaEOGKu53dHxsgTpJ8Ezjek2Kswot0+dKo3xtyDFsWxAwelyaAPpUCopiEOuR+J/YTc4pj4ysLDIjEm4sgv2PYFb3d6mylwkWTzy3rEXhYVR5KDXT12cVpcr8QVgoXynmXdbGWNj6Mr6vzjYk5GbhkMvCtcfGq+whB7cU0GRwKMIGAF7Fk6J9zsb8RdbN943mflPY35STTaL7rGxuh/A2HZjafDeNh0y2l5YmFxgUEG3OVXyA5HZaoV9TWhIRy9UVHtChWWHI7UuL5NFonjsFMcNBV8OcTw41t0yuqrbrPgFCXT7zTF4fW3YQz61oKAvmarxng41ixZyxdbJU6/dnHKpXUu0aET+OnMqloPE1g/wcWOM6zKy8tIOnvBD6ZUuq3DpOrgyAQxTKXDnEKojNEgiYRJZSpDnNyhM+Ou9yMTkYVKaANFW+or1JBBEma20TDJuCkuq1OpcC6H0CQfBHMzr/3557qonr7U9JXxgYXLkyBfWXd5KgSHebJNlCwlKF+4p0x0Tm84=
